### ISSUE TITLE
Embedding story

### ISSUE THREAD

**Issue by fcoury** [aalykiot/dune#158]
Hey there, very cool project.

I am thinking about starting to contribute to the project, but my use case would be to embed dune and allow end users to interact with a rust backend via javascript scripts. I am currently using Deno for that.

Is that something you currently support? If not, would that be something you're willing to accept a PR for?

Thanks again!

**Comment by aalykiot** [comment]
Hello @fcoury 👋 thanks for opening this issue to suggest the embedding idea. 

Here are some points for discussion:
- What makes you wanna switch from a stable / production solution like Deno? (I assume you use `deno_core`)
- Is it possible share more information about your use case?

To be honest, my initial design for Dune was that of a single binary executable (although the event-loop is a different story). As of now, there is no way to embed the runtime into a Rust project. That being stated, I believe it would be possible to package Dune as a crate, given that all essential components are encapsulated within the `JsRuntime` struct:

> The `main.rs` is simply a CLI wrapper using `clap`. 

```rust
// Create new JS runtime.
let mut runtime = JsRuntime::with_options(options);
let mod_result = runtime.execute_module("...", Some(&script));

match mod_result {
  Ok(_) => runtime.run_event_loop(),
  Err(e) => eprintln!("{e:?}"),
};
```

So if a `lib.rs` exports or more precisely re-exports everything from `runtime.rs` then I think it can be embedded.

I need to check if the `execute_module` method is capable of running multiple times (I assume you want module support) because for example the `REPL` interface calls the `execute_script` method multiple times while keeping the context to execute traditional JS scripts (traditional = not ES modules) but manually ticks the event-loop. 

Other than that I can't (currently) think of any more issues. 🤔
