### ISSUE TITLE
Is it possible to use tokio runtime instead of the dune-event-loop?

### ISSUE THREAD

**Issue by linrongbin16** [aalykiot/dune#227]
hi, Thanks to your project, I've learned a lot from it.

When looking into the `JsRuntimeState`, I find out that it implements the javascript `async` keyword through the rust `future`.

Today we usually use the popular `tokio` async runtime. Is it possible to use it along with this js runtime?

Also, could you please give some more design & technical details about the `EventLoop` inside `dune-event-loop`?

**Comment by aalykiot** [comment]
Hello @linrongbin16 👋

Thanks for reviewing Dune, and apologies for the delayed response—my time is currently limited, and I'm prioritizing other projects for now. 

You're almost correct about how the native `JsFuture` trait is utilized in the runtime. It's not exactly about implementing the `async` keyword, as it's also used in cases like `setTimeout` and `setInterval`, but you've captured the main idea behind it. I'm not sure how straightforward it would be to integrate `tokio` into this project, as my original goal was to build the event loop myself, and the entire runtime is structured around that. I’m confident that the `dune-event-loop` crate provides everything the runtime needs, as it’s modeled after `libuv`, which is what `Node.js` uses internally.

I wrote some technical documentation where I cover a few details (in case you haven't seen it yet): https://github.com/aalykiot/dune/blob/main/docs/the-runtime.md

I had considered writing technical documentation specifically for the event loop (and still might), but I just need to find the time and energy to do so. 😅

**Comment by linrongbin16** [comment]
Really thanks for your reply! Looking forward to your tech document about the event loop!

**Comment by linrongbin16** [comment]
hi, I come back and want to share some learning with you, hope I don't bother you.

After reading the source code of this project for quite a time, I realize each pair of `task` and `task_cb` are all sync functions. It seems `task` is usually the slow work, for example download js module from network/http. And `task_cb` is usually pure CPU/memory operations so they are fast.

And for the event loop, (please correct me if I am wrong) it uses a thread pool to execute every task, and then invoke the callbacks.

Let's focus on the `load_import` function and `EsModuleFuture`. They are both sync.

When I am trying to rewrite it with tokio runtime, I found I need to make the `load_import` to async, and the `EsModuleFuture` can be turned into an async function as well.

Because when the module is a URL, `load_import` will be slow, and inside it, we could use some async methods to download the js module from the network/http.

Thanks again to your project, I've learned so much from it!

**Comment by aalykiot** [comment]
Hello again @linrongbin16 👋, since you're likely interested in the internals due to your own project, `rsvim`, I'll do my best to provide detailed answers to your questions. I’m not sure how I would approach integrating `tokio` into Dune, as it wasn’t really designed with `async` Rust in mind, but I imagine it would be a challenge.

1. **`task` vs `task_cb`**

It's easier to grasp the concepts of `task` and `task_cb` when viewed from the perspective of the event loop, rather than focusing on the runtime itself. The event loop (`dune-event-loop`) was specifically designed to be context-aware. With this in mind, a `task` is essentially something you want to offload to the thread pool for execution. This is primarily used (even within Dune) to handle operations that could block a thread, such as `file I/O`, `DNS resolution`, etc. Since both JS and the runtime run on a single thread, blocking it would cause problems. Ideally, for network-related tasks, it's better to rely on network primitives (like Dune does for the `TCP/HTTP` part of the runtime), but that required too much effort, so I opted to use the thread pool for fetching `ES modules` instead.

The core idea is that you submit your `task` to the thread pool, and once the blocking or long-running operation completes, the `task_cb` callback is invoked with the results.

https://github.com/aalykiot/dune-event-loop?tab=readme-ov-file#documentation

```rust
let mut event_loop = EventLoop::default();
let handle = event_loop.handle();

let read_file = || {
    let content = std::fs::read_to_string("./examples/async.rs").unwrap();
    Some(Ok(content.as_bytes().to_vec()))
};

let read_file_cb = |_: LoopHandle, result: TaskResult| {
    let bytes = result.unwrap().unwrap();
    let content = std::str::from_utf8(&bytes).unwrap();
    println!("{}", content);
};

handle.spawn(read_file, Some(read_file_cb));

while event_loop.has_pending_events() {
    event_loop.tick();
}
```

Now, the reason we have the `JsFuture` trait is similar to the issue you encountered with `V8` not being `Send` (https://github.com/rsvim/rsvim/issues/112), meaning you can't transfer `Isolates` or `HandleScopes` to other threads to execute JS code. :(

2. **Event-Loop Ticks**

As I mentioned earlier, the `event loop`, `runtime`, and `V8` (aka JavaScript) all run on a single thread—the main thread. 

While V8 might utilize multiple threads for various tasks, the actual execution of JavaScript happens on the same thread as the runtime. You can think of it as V8 and the runtime sharing the same thread, with execution switching back and forth between them.

When the event loop is ticked, it eventually reaches the `poll phase`: 

```rust
/// Performs a single tick of the event-loop.
pub fn tick(&mut self) {
    self.prepare();
    self.run_timers();
    self.run_poll(); // <------------- THIS ONE.
    self.run_check();
    self.run_close();
}
```

https://github.com/aalykiot/dune-event-loop/blob/main/src/lib.rs#L422-L429
https://github.com/aalykiot/dune-event-loop/blob/main/src/lib.rs#L519

At this stage, a decision is made on whether the event loop should block the main thread and wait for events, such as a `timer` expiring or the `thread pool `completing a `task`, or continue running until the tick ends. The reason we **_block_** the main thread at this point is because there's nothing to do at that moment (we're waiting), and this allows the `OS` to deschedule us from the `CPU`, conserving resources. When there's work to be done, the `OS` will wake us up, and the loop will resume, handing control back to the `runtime`. The runtime will then instruct `V8` to execute some JavaScript..

> Here's more info about low-level kernel polling: https://medium.com/@avocadi/what-is-epoll-9bbc74272f7c

I hope I was able to answer some of your questions and didn’t end up confusing you even more. 😅

Feel free to ask any more questions about Dune's internals. Thanks! 🙂

**Comment by linrongbin16** [comment]
thank you!
